if SERVER then include "simplebank/init.lua" else include "simplebank/cl_init.lua" end
AddCSLuaFile("simplebank/sh_init.lua")
local SimpleBank = include ("simplebank/sh_init.lua")
assert(SimpleBank, "Simplebank failed to load.")
if !SimpleBank then return false end

// Add any custom languages below this line following the convention below (converted phrases will automaticly capitalised):
// SimpleBank:AddLanguage(phrase [string], convertedPhrase [string], language [string])

// Pirate-English Yarg!
SimpleBank:AddLanguage("cancel", "avast", "en-PT")
SimpleBank:AddLanguage("deposit", "stash", "en-PT")
SimpleBank:AddLanguage("deposited", "stashed", "en-PT")
SimpleBank:AddLanguage("withdraw", "grab", "en-PT")
SimpleBank:AddLanguage("withdrew", "grabbed", "en-PT")
SimpleBank:AddLanguage("transfer", "ship to", "en-PT")
SimpleBank:AddLanguage("transferred", "shipped to", "en-PT")
SimpleBank:AddLanguage("account", "treasure", "en-PT")
SimpleBank:AddLanguage("cash", "doubloons", "en-PT")
SimpleBank:AddLanguage("balance", "booty", "en-PT")
SimpleBank:AddLanguage("atm", "trove", "en-PT")
SimpleBank:AddLanguage("bank", "treasure", "en-PT")
SimpleBank:AddLanguage("slogan", "Safely stash ye harrrd earned treasure!", "en-PT")
SimpleBank:AddLanguage("confirm_amount", "inspect treasure before shipping", "en-PT")
SimpleBank:AddLanguage("transfer_alert", "grab shipping notices from other pirates", "en-PT")
SimpleBank:AddLanguage("player", "pirate", "en-PT")
SimpleBank:AddLanguage("doesnt_exist", "not aboard!", "en-PT")
SimpleBank:AddLanguage("cant_afford", "yea cant haggle that!", "en-PT")

// Russian Bliat!
SimpleBank:AddLanguage("to", "игроку", "ru")
SimpleBank:AddLanguage("cancel", "Отмена", "ru")
SimpleBank:AddLanguage("confirm", "Подтвердить", "ru")
SimpleBank:AddLanguage("deposit", "Внести", "ru")
SimpleBank:AddLanguage("deposited", "Внесено", "ru")
SimpleBank:AddLanguage("withdraw", "Вывести", "ru")
SimpleBank:AddLanguage("withdrew", "Выведено", "ru")
SimpleBank:AddLanguage("transfer", "Перевести", "ru")
SimpleBank:AddLanguage("transferred", "Переведено", "ru")
SimpleBank:AddLanguage("transferee", "Получатель", "ru")
SimpleBank:AddLanguage("account", "", "ru")
SimpleBank:AddLanguage("balance", "Баланс", "ru")
SimpleBank:AddLanguage("cash", "Денег", "ru")
SimpleBank:AddLanguage("on_hand", "при себе", "ru")
SimpleBank:AddLanguage("bank", "", "ru")
SimpleBank:AddLanguage("atm", "Банкомат", "ru")
SimpleBank:AddLanguage("eftpos", "eftpos", "ru")
SimpleBank:AddLanguage("slogan", "Гарантия защиты депозита ваших денег.", "ru")
SimpleBank:AddLanguage("confirm_amount", "Подтвердить сумму перед переводом", "ru")
SimpleBank:AddLanguage("transfer_alert", "Получать оповещения о переводе от других", "ru")
SimpleBank:AddLanguage("are_you_sure_want", "Вы уверены, что хотите", "ru")
SimpleBank:AddLanguage("please_enter", "Пожалуйста, введите", "ru")
SimpleBank:AddLanguage("of_transfer_player", " игрока, которому вы хотите перевести.", "ru")
SimpleBank:AddLanguage("select_from_server", "Выбрать с сервера", "ru")
SimpleBank:AddLanguage("device_asking_amount", "Задайте запрашиваемую сумму для этого устройства", "ru")
SimpleBank:AddLanguage("set_player_choice", "Задайте 0, чтобы позволить игроку самому выбрать", "ru")
SimpleBank:AddLanguage("you_received", "Вы получили", "ru")
SimpleBank:AddLanguage("transferred_from", "Переведено от", "ru")
SimpleBank:AddLanguage("please_confirm", "Пожалуйста подтвердите", "ru")
SimpleBank:AddLanguage("find_by", "Найти по", "ru")
SimpleBank:AddLanguage("online", "онлайн", "ru")
SimpleBank:AddLanguage("offline", "офлайн", "ru")
SimpleBank:AddLanguage("name", "имени", "ru")
SimpleBank:AddLanguage("set", "ЗАД.", "ru")
SimpleBank:AddLanguage("pay", "ОПЛ.", "ru")
SimpleBank:AddLanguage("into", "в", "ru")
SimpleBank:AddLanguage("error", "ошибка", "ru")
SimpleBank:AddLanguage("player", "Игрок", "ru")
SimpleBank:AddLanguage("doesnt_exist", "не существует", "ru")
SimpleBank:AddLanguage("cant_afford", "Вы не можете себе этого позволить", "ru")
SimpleBank:AddLanguage("cant_self_trans", "Не можете перевести на самого себя", "ru")